version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: TRZBDWEBStroY
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '123'

    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 127.0.0.1:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:123@db/TRZBDWEBStroY
    
  adminer:
    restart: always
    image: adminer
    ports:
      - 8888:5000

volumes:
  postgres_data:
